name: Test SSH key
  env:
    SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
  run: |
    printf '%s\n' "$SSH_KEY" > /tmp/deploy_key
    chmod 600 /tmp/deploy_key

    echo "Début de la clé :"
    head -n 1 /tmp/deploy_key

    echo "Fin de la clé :"
    tail -n 1 /tmp/deploy_key

    echo "Test de la clé..."
    ssh-keygen -y -f /tmp/deploy_key > /dev/null

    echo "Clé SSH valide."
